version: '3.7'
services:
  bdx-logger-dev:
    image: belldata/vscode-dev:golang-1.14-alpine
    volumes:
      - .:/src/:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    networks:
      - bxlink_network
    container_name: bdx-logger-dev
networks:
  default:
    external:
      name: bridge
  bxlink_network:
    external: true
